apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "0 0 * * *"  # Run daily at midnight
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: node:18
            command:
            - /bin/sh
            - -c
            - |
              cd /app && \
              npm install && \
              npm run backup
            env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: postgres-backup-secrets
                  key: PGHOST
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: postgres-backup-secrets
                  key: PGPORT
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-backup-secrets
                  key: PGDATABASE
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-backup-secrets
                  key: PGUSER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-backup-secrets
                  key: PGPASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-backup-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-backup-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-backup-secrets
                  key: AWS_REGION
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: aws-backup-secrets
                  key: S3_BUCKET
            volumeMounts:
            - name: backup-source
              mountPath: /app
          volumes:
          - name: backup-source
            configMap:
              name: backup-source
          restartPolicy: OnFailure