apiVersion: v1
kind: Secret
metadata:
  name: postgres-backup-secrets
type: Opaque
stringData:
  POSTGRES_HOST: "your-postgres-host"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "your-database"
  POSTGRES_USER: "your-username"
  POSTGRES_PASSWORD: "your-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-backup-secrets
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "your-access-key"
  AWS_SECRET_ACCESS_KEY: "your-secret-key"
  AWS_REGION: "your-region"
  S3_BUCKET: "your-bucket"
