apiVersion: v1
kind: Secret
metadata:
  name: postgres-backup-secrets
type: Opaque
stringData:
  PGHOST: "your-postgres-host"
  PGPORT: "5432"
  PGDATABASE: "your-database"
  PGUSER: "your-username"
  PGPASSWORD: "your-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-backup-secrets
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "your-access-key"
  AWS_SECRET_ACCESS_KEY: "your-secret-key"
  AWS_REGION: "your-region"
  S3_BUCKET: "your-bucket"