services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    volumes:
      - ./minio_data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set backups http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb backups/backups;
      /usr/bin/mc policy set public backups/backups;
      exit 0;
      "

  backup:
    build: .
    depends_on:
      - createbuckets
      - postgres
      - minio
    environment:
      <<: *envars
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: backups

# volumes:
#   postgres_data:
#   minio_data:
