# Reusable envars
x-envars: &envars
  MINIO_ROOT_PASSWORD: postgres
  MINIO_ROOT_USER: postgres
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres

services:
  postgres:
    image: postgres:15
    environment:
      <<: *envars
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    ports: ["5432:5432"]
    volumes: [postgres_data:/var/lib/postgresql/data]

  minio:
    image: minio/minio
    ports: ["9000:9000", "9001:9001"]
    environment:
      <<: *envars
    entrypoint: >
      /bin/sh -c "
        mkdir -p /data/backups;
        minio server --console-address ":9001" /data
      "
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
    volumes: [minio_data:/data]

  backup:
    build: ./backups
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      <<: *envars
      MINIO_ACCESS_KEY: postgres
      MINIO_BUCKET: backups
      MINIO_ENDPOINT: http://minio:9000
      MINIO_SECRET_KEY: postgres

volumes:
  postgres_data:
  minio_data:
