# Reusable envars
x-envars: &envars
  MINIO_ROOT_PASSWORD: postgres
  MINIO_ROOT_USER: postgres
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres

services:
  postgres:
    image: postgres:15
    environment:
      <<: *envars
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      <<: *envars
    command: server --console-address ":9001" /data
    healthcheck:
      test: mc ready local
    volumes:
      - ./minio_data:/data

  minio-setup:
    image: minio/minio
    depends_on:
      minio:
        condition: service_healthy
    environment:
      <<: *envars
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set backups http://minio:9000 postgres postgres;
      /usr/bin/mc mb backups/backups;
      /usr/bin/mc policy set public backups/backups;
      exit 0;
      "

  backup:
    build: ./backups
    depends_on:
      minio-setup:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment:
      <<: *envars
      # POSTGRES_PORT: 5432
      # MINIO_ENDPOINT: http://minio:9000
      # MINIO_BUCKET: backups
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: backups
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: postgres

volumes:
  postgres_data:
  minio_data:
